### ISSUE TITLE
[suggestion] Passer la base leed et les tables en utf8mb4

### ISSUE THREAD

**Issue by Neurozone** [LeedRSS/Leed#431]
MysSQL implémente un format incomplet de l'utf8.

Aussi pour la gestion des caractères unicode, il est recommandé par MySQL d'employer le charset utf8mb4 qui permet de gérer les caractères unicode sur 4 bits

Florianne

**Comment by Sbgodin** [comment]
Merci pour la proposition. Aurait-tu des liens ou des tests en relation avec utf8mb4 ?

**Comment by Tabrisange** [comment]
Précise ta question ?

**Comment by Tabrisange** [comment]
https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html

**Comment by Sbgodin** [comment]
Bien vu ! J'imaginais que l'_utf8_ de Mysql gérait tout Unicode. En fait, _utf8_ reste cantonné à l'unicode jusqu'à 3 octets alors que _utf8mb4_ gère les 4 octets. _utf8_ Cela colle à la grande majorité des langues des utilisateurs de Leed. Ceci dit, il y a tout de même des symboles et autres caractères linguistiques (ex. 𝌆) qui poseront problème.
Je conjecture que _mb4_ signifie _Multi Byte 4_, soit 4 octets gérés en multi-octet.

D'après ce site, https://mathiasbynens.be/notes/mysql-utf8mb4, il faut agir au niveau du serveur mysql, de la base de données et du client. Pour ce qui nous intéresse ici, il faudra :

1. Modifier la base de données. C'est-à-dire qu'il faudra le faire pour les bases de données crées et les bases de données déjà existantes.
1. Modifier le code source de Leed. Rien de délicat, du remplacement de _utf8_ car _utf8mb4_ et un brin de test. Par contre, cela rendra Leed potentiellement incompatible avec une base restée en _utf8_. Ou alors, on utilise une variable de configuration ?
1. Modifier le code de génération de la base de données. Comme précédemment, rien de délicat mais il y a des tests à faire.
1. Modifier le serveur Mysql, à savoir le mettre à jour.

Comme la mise en place de tout cela prendra des tests et du temps, j'imagine qu'il faudra créer une sous-branche _utf8mb4_ de _dev_ et que quelqu'un y reste pour tester ces modifications. Cette branche récupère les développements de _dev_ et s'assure de la non-régression.

Par contre, à mon humble avis, difficile de forcer une mise à jour de la base comme je l'ai fait [hier](3356aa3cf72eaff8642153fb439154e66e44dbfa). Sauf nouvelle installation, le passage à l'utf8mb4 devra être volontaire.

**Comment by Tabrisange** [comment]
Pour ma part je l'ai fait et j'ai aussi changé la collation des colonnes texte ou varchar :)

Mais en effet c'est une opération à ne pas prendre à la légère

**Comment by Sbgodin** [comment]
Tu as aussi modifié le code de Leed, alors ? Les collations, charset, etc. ?

**Comment by Tabrisange** [comment]
Non du tout

**Comment by Sbgodin** [comment]
On teste, alors. Arrives-tu à créer une catégorie nommée « test 𝌆 test » ?

**Comment by Tabrisange** [comment]
Je te répondrais plus tard ce soir une fois chez moi pour tester, mais j'ai noté que suite à ça, des titres de posts qui contenaient des caractères en utf8 sur 4 octets ont été bien insérés

**Comment by Tabrisange** [comment]
"On teste, alors. Arrives-tu à créer un dossier nommé « test 𝌆 test » ?"

Non et je n'ai aucun message d'erreur nulle part :o

**Comment by Sbgodin** [comment]
Si tu n'as modifié que la base de données sans toucher à Leed, c'est logique. Tous les appels Mysql doivent déclarer l'encodage _utf8mb4_. Ce qui semble répondre à la question « peut-on modifier la base de données et laisser Leed tel quel ? Non ».

**Comment by Tabrisange** [comment]
Oui mais je suis étonnée que leed ne log pas les exceptions rencontrées, cela pourrait être pratique.

Je ne suis pas fan de gérer la création des tables directement dans l'entité, je trouve ça usine à gaz

**Comment by Sbgodin** [comment]
Ce serait difficile de changer cela, c'est au cœur de l'application. L'intérêt, c'est que la définition des données est presque indépendance du système de gestion de base de données et qu'elle est intégrée dans les classes concernées. Les tables dédiées sont automatiquement crées si elles n'existent pas. Il n'y a pas de script de création de base à proprement parler.

Quant aux log, effectivement il n'y a rien. Selon l'article su-cité (https://mathiasbynens.be/notes/mysql-utf8mb4) l'erreur serait silencieusement escamotée au niveau de Mysql. C'est à ce niveau-là qu'il faudrait capturer l'erreur.

**Comment by Tabrisange** [comment]
Elle n'est pas silencieusement escamotée vu que je me suis retrouvée avec des exceptions avant d'avoir fait la modification :)

**Comment by Sbgodin** [comment]
Peux-tu préciser les messages obtenus et les conditions d'exécution ?

**Comment by FlorianneRaven** [comment]
Depuis le passage à leed 1.8.2 le dossier se crée sous cette forme:
"test ???? test"

**Comment by FlorianneRaven** [comment]
Je n'ai plus d'erreurs non plus.

**Comment by Sbgodin** [comment]
Hello !

Peux-tu préciser le contexte où se forme ce dossier ? À l'installation à partir de zéro ?

**Comment by FlorianneRaven** [comment]
Lors de la création d'un nouveau dossier sur leed 1.8.2
