### ISSUE TITLE
file_get_contents() sur une url

### ISSUE THREAD

**Issue by spyjo** [LeedRSS/Leed#443]
Bonjour,

Je viens de voir dans mes logs php que j'avais cette erreur (en étant dans l'admin des plugins):

`[31-Jan-2017 14:43:40 Europe/Paris] PHP Warning:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /var/www/XXXXXX/leed/Plugin.class.php on line 196
[31-Jan-2017 14:43:40 Europe/Paris] PHP Warning:  file_get_contents(https://api.github.com/orgs/Leed-market/repos): failed to open stream: no suitable wrapper could be found in /var/www/XXXXXX/leed/Plugin.class.php on line 196
[31-Jan-2017 14:43:40 Europe/Paris] PHP Warning:  Invalid argument supplied for foreach() in /var/www/XXXXXX/leed/Plugin.class.php on line 202
`

En effet allow_url_fopen est à 0 dans ma config php, comme je pense la plupart des configurations php. Peut-être vaut-il mieux remplacer cet appel par curl (ou a pire faire un failback pour garder les 2)

Merci

**Comment by Sbgodin** [comment]
Hello, content de te lire ici bas. Peux-tu fournir la version de Leed que tu utilises, ou mieux, le numéro de la révision ?

**Comment by spyjo** [comment]
J'utilise la version stable 1.8 qui vient d'être releasé ce matin

**Comment by Sbgodin** [comment]
Peux-tu faire une nouvelle installation avec une base de données vierge ? En principe, ça devrait bloquer... Dis-nous ce qui en sort ?

**Comment by spyjo** [comment]
tu parles de bloquer au niveau du pré-requis à l'installation ?

sur un leed vierge, quand je suis sur install.php , c'est écrit:

Pré-requis à l'installation
Succès :
Permissions sur le dossier courant : OK
Fonction requise 'mysqli_connect' : OK
Fonction requise 'file_get_contents' : OK
Fonction requise 'file_put_contents' : OK
Fonction requise 'curl_exec' : OK
Compatibilité version PHP (5.6.29-0+deb8u1) : OK
Gestion du timeout : OK

**Comment by Sbgodin** [comment]
Okkaayy... Ce qui m'amène deux questions :
1) Comment vérifier, sans trop de bidouille, que le file_get_content() marche même si la fonction existe ?
2) @spyjo, utilisais-tu Leed avant ou viens-tu juste de l'essayer ? Cette erreur aurait dû surgir bien avant cette mise à jour.

**Comment by spyjo** [comment]
si vraiment le allow_url_fopen est obligatoire, il peut être testé avec ini_get('allow_url_fopen') en théorie
mais à mon avis il vaudrait mieux gérer le cas pour autoriser cette valeur à 0 car ça reste non secure de l'activer

oui j'utilise leed depuis longtemps, mais à vrai dire je ne m'étais jamais intéressé à la partie plugins :) c'est juste aujourd'hui en relisant le changelog de la 1.8 que je suis allé voir et comme la page des plugins indique "Tous les plugins sont déjà installés ou aucun n'a pu être trouvé." , je me suis douté qu'il y avait un bug, et c'est là que j'ai vu le soucis dans les logs php.

**Comment by Simounet** [comment]
`allow_url_fopen is on by default`
Ce qui n'empêche pas qu'il est conseillé d'utiliser `cURL` pour ce genre de manipulations. On peut l'ajouter au précos d'installation et n'en faire un blocage que si `cURL` est absent ET `allow_url_fopen = 0`. Qu'en pensez-vous ?

**Comment by Sbgodin** [comment]
Effectivement. _cUrl_ est utilisé par SimplePie. Lequel utilise _get_file_contents()_ avec des url avec la gestion des greffons. Du coup, je suggère de modifier la gestion des greffons (@Simounet ?) afin de pouvoir s'en passer au mieux. Ensuite, j'adapterai l'installeur pour qu'il nécessite la présence de deux, ou d'un seul, en fonction des tests.

**Comment by Simounet** [comment]
Oui, je prends, j'ai déjà quelque chose qui fonctionne. Et l'installeur demande déjà la présence de `cURL`.

**Comment by spyjo** [comment]
J'ai appliqué la modification, je confirme que tout est ok pour les plugins maintenant, listing et installation :)

**Comment by Simounet** [comment]
Super. Merci pour ton retour !
