### ISSUE TITLE
Aucun Flux à mettre à jour.

### ISSUE THREAD

**Issue by Sigri44** [LeedRSS/Leed#453]
Bonjour à tous,

Leed v1.8 sur Synology avec Thème Leedvibes.

L'intégration s'est bien passé, j'ai eu mes flux qui sont arrivés, mais depuis, aucune actualisation.
J'ai installé LeedUpdate mais ce n'est pas mieux.
Lorsque que je fais la synchro en haut de la home : "Aucun nouvel article n'est disponible."
Lorsque que je fais MàJ manuelle des flux dans les réglages : "Aucun flux à mettre à jour."
Lorsque j'accède à l'URL de mon cron : "Aucun flux à mettre à jour."
(http://XX.XX.XX.XX/leed/action.php?action=synchronize&code=b6b89XXXXX)

Tâche Cron : 
`wget --no-check-certificate -q -O /var/services/web/leed/logsCron 'http://XX.XX.XX.XX/leed/action.php?action=synchronize&code=b6b89XXXXX'`

J'ai essayé de désactiver le cache, même souçis.

Merci.

**Comment by Sbgodin** [comment]
Hello,

Peux-tu indiquer quelle version de Leed tu utilises ? Soit le fichier zip particulier ou la révision précise. Utilises-tu d'autres greffons ? Sur une installation neuve, à côté, utilisant une autre base, est-ce que ça fait pareil ?

**Comment by Sigri44** [comment]
Version 1.8 :)
L'installation est neuve, j'avais déjà eu un souçis sur Leedvibes, j'ai fait une réinstall.
J'ai juste leedicons, leedstats, leedvibes et LeedSmartFeedsUpdate mais qui ne marche pas.

**Comment by Sbgodin** [comment]
Je suppose que c'est la version stable. Sans greffons du tout, c'est comment ?

**Comment by Sigri44** [comment]
Yes ! Pareil.

**Comment by Simounet** [comment]
Si je me souviens bien, tu avais déjà d'autres soucis. Aurais-tu les logs d'erreurs à nous donner stp ?

**Comment by Sigri44** [comment]
Yes Simounet :) Depuis la résolution de nos souçis ensemble, j'ai réistall, tous tes conseils ont marchés mais j'ai des souçis d'update (et qui finalement ne viennent pas de ton plugins ;))
C'est ou déjà les logs ? ^^
/var/services/web/leed/logsCron vous suffit ?

**Comment by Simounet** [comment]
Il faudrait les logs de PHP. /var/log/apache2/error.log au pif vu que je ne connais pas trop Synology.

**Comment by Sigri44** [comment]
J'ai nginx et aucune erreur.

**Comment by Simounet** [comment]
Tu n'as aucune mise à jour de flux après la première récupération à l'installation, c'est bien ça ? Si tu ajoutes un nouveau flux, est-il parsé et les articles sont-ils ajoutés ? Les flux actuels ont-ils bien de nouveaux articles ?

**Comment by Sigri44** [comment]
Oui c'est ça !
Si je mets un nouveau flux il me le surligne rouge de partout. Aucun nouveau flux

**Comment by Sbgodin** [comment]
Quelle version de Php utilises-tu ?

**Comment by Sigri44** [comment]
5.6 :)

**Comment by Sbgodin** [comment]
Si tu as accès à la ligne de commande, peux-tu lancer "php action.php" à partir du répertoire de Leed et nous indiquer ce qu'il en sort ?

**Comment by Sigri44** [comment]
```
PHP Fatal error:  Class 'mysqli' not found in /volume1/web/leed/MysqlConnector.class.php on line 23
Fatal error: Class 'mysqli' not found in /volume1/web/leed/MysqlConnector.class.php on line 23
```

**Comment by Simounet** [comment]
Il te faut installer l'extension mysqli pour PHP (`php5-mysqli`). Je ne sais pas vraiment comment ça se passe sur un Synology. Ce qui m'étonne c'est que l'installation n'aurait pas dû se lancer vu que c'est un pré-requis. As-tu changer quelque chose depuis ?

**Comment by Sigri44** [comment]
Non rien changer.
Depuis le nouveau flux, il m'as fait une synchro (la première fois, après 24h je pense), et depuis bloqué pareil.
Bizarre j'ai vu plusieurs personnes avec leed sur syno sans problèmes ^^

**Comment by Simounet** [comment]
Peux-tu créer ce fichier et nous en donner le résultat ?
```php
<?php
echo function_exists('mysqli_connect') ? 'Ok' : 'No';
```

**Comment by Sigri44** [comment]
J'ai MariaDB, je sais pas si ça peut jouer.

`Parse error: syntax error, unexpected 'function_exists' (T_STRING) in /volume1/web/leed/test.php on line 2`

**Comment by Simounet** [comment]
As-tu d'autres projets en PHP qui tournent sur ton Syno ? L'impression que j'ai avec les éléments que tu me donnes, c'est que ton install PHP/MySQL est cassée.

**Comment by Sigri44** [comment]
Non je n'ai que ça qui tourne.
Bizarre c'est tout neuf, le NAS est neuf, j'ai juste installé MariaDB, phpmyadmin, et PHP 5.6 (de mémoire) pour que ça fonctionne.

**Comment by Simounet** [comment]
Je n'ai malheureusement pas de connaissance en Syno mais je peux te propose de venir sur IRC un soir pour essayer de dépatouiller ça ensemble.

**Comment by Sigri44** [comment]
Nop ! Quel channel ?

**Comment by Simounet** [comment]
#Leed sur freenode.

**Comment by Simounet** [comment]
Bonjour @Sigri44, je ne sais pas si tu es encore utilisateur de Leed depuis le temps. Qu'en est-il de ce soucis ? Puis-je fermer le ticket ?
Merci d'avance.
