### ISSUE TITLE
Mise à jour de SimplePie

### ISSUE THREAD

**Issue by Sbgodin** [LeedRSS/Leed#462]
[SimplePie](https://github.com/simplepie/simplepie/), la bibliothèque de téléchargement des flux, devrait être mise à jour. Il y a des modifications (faca782) qu'il faut remonter à SimplePie, soit à prendre en compte dans une divergence.

**Comment by Simounet** [comment]
Vu ce que donne un `git log SimplePie.class.php`, je pense qu'il y a plus que ton commit à remonter.

**Comment by Sbgodin** [comment]
Aucun problème :+1: On va squasher tout ça, faire une requête d'intégration et roule ^^

**Comment by Simounet** [comment]
La librarie a pas mal changé depuis notre dernière mise à jour, il y a
notamment eu une grosse séparation en plusieurs fichiers donc à voir. Il
faudra le faire de tous façons.

**Comment by Tabrisange** [comment]
Je confirme :

Warning: A non-numeric value encountered in /data/www/rss.neurozone.fr/SimplePie.class.php on line 8849

En php 7.1 leed est inutilisable, même avec la dernière version

**Comment by Sbgodin** [comment]
Merci pour le retour. L'erreur se déclenche dans la fonction _date_w3cdtf()_, à un endroit qui ne devrait pas être sensible à php7.1. En théorie...

Dans quel cas obtiens-tu le _Warning_ ? Est-ce la sortie du log ? Cela s'affiche sur le navigateur ? Si oui, à quelle occasion ?

Cela le fait sur tous les flux ?

**Comment by Tabrisange** [comment]
Un exemple : 

0.808s | Framboise 314, le Raspberry P…

Warning: A non-numeric value encountered in /data/www/rss.neurozone.fr/SimplePie.class.php on line 8849

Warning: A non-numeric value encountered in /data/www/rss.neurozone.fr/SimplePie.class.php on line 8849

Par contre je ne sais pas quel flux exactement fait ça.

Et sur une install vierge de apache + php, leed ne fonctionne pas, il faut au moins le module php-gd ^^
(pour info je suis en centOS 7.3 et php 7.1)

Ah et un autre problème : 
ça m'a créé un trigger avec un definer que j'utilise en local sur mon linux et pas avec l'utilisateur qui a les droits sur la base.

quand j'ai fait un export/import de la abse sur le nouveau serveur, l'utilisateur précédent n'étant pas créé, les inserts plantent silencieusement, impossible d'avoir l'erreur en question, alors que quand je teste un insert à la main : 

MariaDB [leed]> INSERT INTO `leed_event`(`id`,`guid`,`title`,`creator`,`content`,`description`,`link`,`unread`,`feed`,`favorite`,`pubdate`,`syncId`)VALUES("0","http://c-cassandra.tumblr.com/post/158176319155","And there’s no going back.","","<img src=\"http://68.media.tumblr.com/e081a3c0b1559a659cf007f0c61d0eed/tumblr_omj3zrnxoJ1tcbp8vo1_500.jpg\"><br><br><p>And there&rsquo;s no going back.</p>","<img src=\"http://68.media.tumblr.com/e081a3c0b1559a659cf007f0c61d0eed/tumblr_omj3zrnxoJ1tcbp8vo1_500.jpg\"><br><br><p>And there&rsquo;s no going back.</p>","http://c-cassandra.tumblr.com/post/158176319155","1","312","0","1489031400","1489051801");

ERROR 1142 (42000): TRIGGER command denied to user 'dba'@'localhost' for table 'leed_event'

Cette erreur n'est affichée nulle part

Je crois que je vais vous servir de beta testeuse à la fin ^^

**Comment by Tabrisange** [comment]
Dans quel cas obtiens-tu le Warning ? 
=> lors de la synchronisation des flux, que ça soit en cli ou en web

Est-ce la sortie du log ? 
=> oui

Cela s'affiche sur le navigateur ? 
=> oui 

Si oui, à quelle occasion ?
=> un clic sur le bouton synchroniser

Cela le fait sur tous les flux ?
=> non, veux tu un exemple de flux ?

**Comment by Sbgodin** [comment]
Oui, s'il-te-plaît. Je voudrais reproduire le problème chez moi.

**Comment by Tabrisange** [comment]
Ce flux : 
http://authueil.fr/feed/atom

provoque des erreurs

**Comment by Sbgodin** [comment]
Bien vu pour GD ! J'ai rectifié sur la [dev](a7d084c7b1c0aec6ccf5a3ccbc8838f5ec9104cd). Je testerai le reste.

**Comment by Tabrisange** [comment]
Je ne dirais pas non à avoir accès à la dev pour faire des tests de mon côté ^^
*sifflote d'un air innocent*

**Comment by Simounet** [comment]
https://github.com/LeedRSS/Leed/tree/dev 😉

**Comment by Sbgodin** [comment]
Tu peux aussi faire ceci, sur ta divergence :
```
git remote add leedrss https://github.com/LeedRSS/Leed/tree/dev
git fetch leedrss
```
Ainsi tu as tes validations et celles de Leedrss/leed.

**Comment by Sbgodin** [comment]
J'ai mis à jour SimplePie dans la branche [Leed/majRainTpl](https://github.com/LeedRSS/Leed/tree/majRainTpl). Chez moi ça marche, testez chez vous s'il-vous-plaît. Il me faudrait des retours depuis Php 5 et Php 7.

Je confirme le souci avec SimplePie et Php 7.0/7.1. J'ai donc mis à jour SimplePie (134d88e en version [1.4.3-2-geb6dd2d](https://github.com/simplepie/simplepie/commit/eb6dd2d578dd62a1eec68b60cdda8c4a38a8de49)) et appliqué seulement mon dernier patch, celui qui enlève le référent (c072e15).

**Comment by Simounet** [comment]
Je suis passé sur ta branche, j'ai ajouté le flux et n'ai constaté aucun soucis. PHP 7.0.15 ici.

**Comment by Tabrisange** [comment]
Je suis passée sur cette branche.

Plus d'erreurs affichées, par contre curieusement quand je clique sur le bouton de mise à jour des flux je n'ai qu'uin carré blanc qui s'affiche.

quand j'ouvre la console de firefox et que je regarde la réponse de la requête ajax, j'ai ça qui s'affiche: 

Recharger la page pour obtenir le code source pour: https://rss.neurozone.fr/action.php?action=synchronize
&format=html&code=49efed9906

**Comment by Sbgodin** [comment]
Étrange, cela le fait aussi quand tu reviens sur Leed/dev ? Note, j'ai édité ton commentaire précédent pour en retirer le code, qui doit rester secret. Il vaudrait mieux que tu le changes (dans la bdd, table configuration, ligne synchronisationCode).

**Comment by Sbgodin** [comment]
Ah tiens, je sais pourquoi il y a un soucis de mise en page chez toi ^^ Tu as activé l'affichage des erreurs sur la page et il y a une erreur dans le code... J'ai mis à jour la branche leed/majRainTpl. Je reverserai ce correctif sur la dev un peu plus tard.

**Comment by Tabrisange** [comment]
D'accord

J'aimerais quand même bien voir les erreurs dans mes fichiers de log, c'est frustrant de ne rien voir

Sinon avec le nouveau simplepie ça marche beaucoup mieux :)

**Comment by Sbgodin** [comment]
Dans le _php.ini_ il y a trois variables utiles :

1. __display_errors__ : afficher ou non les erreurs à l'écran
1. __error_reporting__ : quels types d'erreur signaler
1. __log_errors__ : ajouter les erreurs dans le log

Donc, ce que tu dois sûrement vouloir, c'est 

- __display_errors__ : Off (rien à l'écran)
- __error_reporting__ : E_ALL (tout est rapporté)
- __log_errors__ : On (erreurs dans le log)

Ensuite, un `tail -f /var/log/apache2/error.log` (sous linux) te rapporte en temps réel les erreurs.

**Comment by Sbgodin** [comment]
J'ai mis à jour _dev_ avec la nouvelle version de SimplePie. La branche _majRainTpl_ (qui aurait dû être nommée _majSimplePie_) est supprimée. Les validations ont été rebasée sur _dev_.

**Comment by FlorianneRaven** [comment]
Alors dans mon fichier de vhost j'ai ça : 
ErrorLog /var/log/httpd/errorxxx.log
CustomLog /var/log/httpd/access.xxx.fr.log combined

Et rien ne s'affiche à l'écran toujours 
Et pour le php.ini j'ai ça:

display_errors = On
error_reporting = E_ALL
log_errors = On

error_log = /var/log/httpd/php_errors.log

**Comment by FlorianneRaven** [comment]
Je précise que je suis en CentOS 7.3 et php 7.1

**Comment by Sbgodin** [comment]
Tente de faire un fichier ne contenant qu'une erreur, tu verras bien si ça déclenche...
