### ISSUE TITLE
Import de flux OPML cassé dans Leed 1.8.2 

### ISSUE THREAD

**Issue by HacKurx** [LeedRSS/Leed#466]
Bonjour,

L'importation d'un fichier opml ne fonctionne plus avec la version de Leed 1.8.2.
Voici l'erreur dans les logs : 
PHP Warning:  require_once(SimplePie.class.php): failed to open stream: No such file or directory in /var/www/Opml.class.php on line 150, referer: http://10.1.1.2/leed/action.php?action=importForm

L'erreur vient du faite qu'avec cette version un fichier utilisé n'hésite plus :
www/Opml.class.php:        require_once("SimplePie.class.php");

La solution consiste alors à remplacer dans le fichier la valeur "SimplePie.class.php" par "SimplePie.compiled-1.4.3-2-geb6dd2d.php".

Ou bien pour les utilisateurs de cette version de créer un lien symbolique :
ln -s SimplePie.compiled-1.4.3-2-geb6dd2d.php SimplePie.class.php

Merci, cordialement

**Comment by Simounet** [comment]
Bien vu @HacKurx !
@Sbgodin n'aurait-il pas été plus judicieux de mettre la référence à la version de SP utilisée dans le commit de mise à jour plutôt que de nous obliger à mettre à jour toutes les références à ce fichier ?

**Comment by Sbgodin** [comment]
Je confirme le problème. @Simounet, la modification suggérée par @HacKurx est bonne. Mais effectivement, remettre le nom de fichier sans la version réglerait aussi le problème.

J'ai préféré mettre la version dans le nom du fichier afin que même ceux qui récupèrent depuis une archive (ou s'ils suppriment le _.git_) soient quand même sûrs du numéro de version. Si ça pique trop, je peux retirer le numéro de version du nom de fichier et mettre à jour les références de _action.php_ et _Opml.class.php_.

**Comment by Simounet** [comment]
Je pense qu'il vaut mieux reprendre l'ancien nom. Le numéro de version et le numéro de build se trouvent à l'intérieur du fichier de toutes façons.

**Comment by Sbgodin** [comment]
Merci @HacKurx !

**Comment by HacKurx** [comment]
De rien, avec plaisir ;)
