### ISSUE TITLE
Installation impossible

### ISSUE THREAD

**Issue by will-morel** [LeedRSS/Leed#470]
Hello,

Ancien utilisateur de Leed, je décide aujourd'hui de le réinstaller mais :
à la soumission de l'install.php j'ai l'erreur suivante : "constant.php" not found!

Soit, je fais donc un touch constant.php Je me retrouve alors avec cette erreur : Leed est déjà configuré. Supprimez ou renommez le fichier de configuration.

Que faire ?

**Comment by Simounet** [comment]
Salut,
Es-tu parti d'une install fraîche ou as-tu réutilisé un dossier existant ?

**Comment by will-morel** [comment]
Wow, my bad, un -R manquant sur un chmod.
Vraiment navré !

Continuer le boulot les gars, vosu faites ça bien  :)

**Comment by Simounet** [comment]
Pas de soucis. Content de voir que tu as pu résoudre ton soucis. Tu es bien en 1.8.3 ?

**Comment by will-morel** [comment]
Dernière version sur la branche Master ! :)
Aucun autre problème à signaler, ça fonctionne du feu de dieu
________________________________
