### ISSUE TITLE
disponibilité de php-xml pourrait être vérifiée à l'installation

### ISSUE THREAD

**Issue by medvejonok79** [LeedRSS/Leed#471]
Bonjour,

j'ai installé Leed, mais cela ne fonctionnait pas au début quand je voulais rajouter un flux RSS. Lorsque j'ajoutais le flux, il appelait la page action.php, mais cela affichait une page vide (sans message d'erreur).

Après un peu de débuggage, j'ai identifé que la classe Feed essayait d'appeler une fonction de parsage XML. Qui aurait du être fournie sur mon installation par le package apt  php5.6-xml  , mais qui n'était pas installé.

Donc à l'installation si l'existence de ce package était vérifiée, cela éviterait la page blanche que j'ai eu et qu'un utilisateur moins à l'aise avec le code source aurait du mal à débugger ou à décrire.

**Comment by Sbgodin** [comment]
Hello,

Merci d'avoir signalé ce bug. Il est en cours de rectification, j'ai soumis le correctif à l'équipe. Comme nous sommes en train de basculer en auto-hébergement, les modifications sont visibles sur le nouveau dépôt :

https://git.idleman.fr/LeedRSS/Leed/pulls/1

**Comment by Simounet** [comment]
Fixé par 2a0d372e. Je ferme.
