### ISSUE TITLE
XML invalide avec flux de BlogoText

### ISSUE THREAD

**Issue by vekin03** [LeedRSS/Leed#473]
J'ai ajouté les flux de deux blogs tournant avec le CMS BlogoText et j'obtiens dans les deux cas l'erreur suivante :

> _[URL]_ is invalid XML, likely due to invalid characters. XML error: > required at line 21, column 6

Les deux flux sont https://lehollandaisvolant.net/rss.php et https://couleur-science.eu/rss.php

Je ne sais pas si l'erreur est du côté de BlogoText, de Leed ou les deux.

**Comment by Simounet** [comment]
Hmmm, très étrange car j'ai lehollandaisvolant depuis plusieurs années dans mon Leed sans aucun problème. Je viens de tester avec une version fraîche de Leed et pas de soucis non plus. Pourrais-tu me dire quelle version de PHP tu as ? Es-tu en auto-hébergé ou sur un hébergeur tiers ?

**Comment by vekin03** [comment]
Voilà toutes les informations : https://feed.vuilleumier.tv/phpinfo.php

Il s'agit d'un hébergement mutualisé OVH.

**Comment by Simounet** [comment]
Il semblerait qu'une protection empêche les serveurs d'OVH d'accéder à ces flux car j'y accède très bien depuis mon Leed auto-hébergé mais sans succès depuis celui qui est sur mon mutualisé OVH. Je vais essayer de contacter l'auteur de ces blogs. Je te tiens au courant.

**Comment by timovn** [comment]
C’est bien un problème d’accès au serveur qui héberge (entre-autre) mes sites. 

D’autres personnes aussi m’ont signalé (plus ou moins récemment) que mon site était bloqué sur certains FAI belges. Ni Blogotext ni Leed ne sont en cause.

Je n’ai pas de solutions pour le moment, mais je vais voir tenter de voir ce qui se passe.

**Comment by Simounet** [comment]
Ok, ça marche. Merci pour ton retour. Je ferme donc ce ticket.
