### ISSUE TITLE
Erreur lors de la synchronisation des flux

### ISSUE THREAD

**Issue by jarobase** [LeedRSS/Leed#474]
PHP Version 7.2.3, tous voyants au vert lors de l'installation.
mariadb 10.1.31-1
PHP installé dans un container docker. (php:7.2-apache)
```
Type de synchronisation : Synchronisation complète… 01/04/2018 20:49:29

0.471s | Archlinux.fr

Warning: Error while sending QUERY packet. PID=25 in /var/www/html/secure/leed/MysqlEntity.class.php on line 377

Fatal error: Uncaught Error: Call to a member function fetch_assoc() on boolean in /var/www/html/secure/leed/MysqlEntity.class.php:280 Stack trace: #0 /var/www/html/secure/leed/MysqlEntity.class.php(310): MysqlEntity->loadAll(Array, NULL, 1, '=') #1 /var/www/html/secure/leed/Feed.class.php(107): MysqlEntity->load(Array) #2 /var/www/html/secure/leed/Feed.class.php(346): Feed->parse(1522608569, 1, '0', '0') #3 /var/www/html/secure/leed/action.php(68): Feed->synchronize(Array, 'Type de synchro...', false, Object(Configuration), 1522608569.8102) #4 {main} thrown in /var/www/html/secure/leed/MysqlEntity.class.php on line 280
```
L'erreur bloque la récupération des flux.
Résultat attendu: la synchronisation des flux.

**Comment by jarobase** [comment]
Le problème provient du flux suivant: [arduino103.blogspot.com](https://arduino103.blogspot.com/feeds/posts/default). J'ignore pourquoi. En enlevant le flux, tout fonctionne. Firefox le reconnaît comme un flux normal.

**Comment by Sbgodin** [comment]
J'ai ajouté le flux. Rien à signaler, évidemment... C'est embêtant puisque Leed devrait signaler une erreur mais pas planter ainsi. Ça le fait encore ?

**Comment by jarobase** [comment]
Non évidemment. Peut-être qu'un article contenait du formatage XML non conforme, une balise mal fermée ou un ">" non échappé. Je pense que le ticket peut être fermé car on arrivera pas à le reproduire tout de suite. Je créerai un autre ticket et commenterai ici si le problème se représente.
