### ISSUE TITLE
Implement HTTP cache revalidation

### ISSUE THREAD

**Issue by da2x** [LeedRSS/Leed#475]
Please implement HTTP cache revalidation to save bandwidth for users and websites alike. It’s super-easy to implement: save the values from the `Last-Modified` and `ETag` HTTP response headers when updating a feed. The next time that feed is updated, return the same values in the `If-Modified-Since` and `If-None-Match` request headers. Servers will respond with 304 Not Modified instead of retransmitting the entire feed.

Feed updates should be faster as well as there wouldn’t be any data to process as a nice bonus.

Once you’ve got that working, you can also add support for delta feed updates (server only sends new entries instead of the entire feed) by adding `A-IM: feed` request header when the request has either or both a `If-Modified-Since` and `If-None-Match` request header.

See the [RFC 7234 Caching in HTTP](https://tools.ietf.org/html/rfc7234) and [best practises for feed clients](http://ctrl.blog/entry/feed-caching) for details.

**Comment by Simounet** [comment]
You're right and we will.

**Comment by Simounet** [comment]
Hi @da2x , I'm doing some cleaning here. I dig a little bit for your proposal and Leed is using SimplePie to get feeds. We already have all we need if cache is enabled. I found your PR on [the SimplePie repository][https://github.com/simplepie/simplepie/pull/477)!
Thanks again to help project like our to be as light as it should be! Take care.
