### ISSUE TITLE
utf8mb pour gestion des emojis

### ISSUE THREAD

**Issue by Neurozone** [LeedRSS/Leed#478]
J'avais un flux rss qui me posait problème dans Leed car impossible de l'importer dans la base à cause de l'emoji dans le titre.

La solution est de convertir la table leed_event avec:

ALTER TABLE leed_event CONVERT TO CHARACTER SET utf8mb4 [COLLATE utf8mb4_unicode_ci];

ET

dans MysqlConnector.class.php

de modifier:

public function __construct(){
        $this->connection = new mysqli(MYSQL_HOST,MYSQL_LOGIN,MYSQL_MDP,MYSQL_BDD);
        $this->connection->set_charset('utf8mb4');
        $this->connection->query('SET NAMES utf8mb4');
    }

Et tout passe correctement

**Comment by Simounet** [comment]
Hello @Neurozone, je suis en train de préparer une mise à jour de Leed avec ces infos, serais-tu prêtes à la tester ? Je vais passer tous les champs texte en utf8mb4.

**Comment by Neurozone** [comment]
Mmmm je veux bien la tester mais j'ai quasiment réécrit une bonne partie du code sur mon repo (pas finalisé)

Si tu as du temps pour en discuter je serais intéressée

**Comment by Neurozone** [comment]
@Simounet  comment peut-on se contacter ? :)

**Comment by Simounet** [comment]
contact at simounet dot net :mailbox:

**Comment by Simounet** [comment]
Tu peux tester la branche `feat/use-utf8mb4` si ça te convient.

**Comment by Simounet** [comment]
@HacKurx si tu as du temps et que tu veux tester, je suis preneur de retours d'utilisateurs de la branche `feat/use-utf8mb4`.

**Comment by HacKurx** [comment]
@Simounet pas de problème, ce week-end je teste.

**Comment by HacKurx** [comment]
> @HacKurx si tu as du temps et que tu veux tester, je suis preneur de retours d'utilisateurs de la branche `feat/use-utf8mb4`.

Nouvelle installation impossible.

```
Leed error: COLLATION 'utf8mb4_general_ci' is not valid for CHARACTER SET 'utf8'

Leed query: CREATE TABLE IF NOT EXISTS `leed__configuration` (`id`  int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY  NOT NULL,`key`  VARCHAR(225) CHARACTER SET utf8 COLLATE utf8mb4_general_ci  NOT NULL,`value`  TEXT CHARACTER SET utf8 COLLATE utf8mb4_general_ci  NOT NULL,UNIQUE `uniquekey` (`key`))\n        ENGINE InnoDB,\n        DEFAULT CHARACTER SET utf8 COLLATE utf8mb4_general_ci\n        ;

Leed query: CREATE TABLE IF NOT EXISTS
```

**Comment by Simounet** [comment]
Désolé pour ça, j'en avais oublié un bout. Ça devrait aller mieux si tu récupères la dernière version de la branche.

**Comment by HacKurx** [comment]
> Désolé pour ça, j'en avais oublié un bout. Ça devrait aller mieux si tu récupères la dernière version de la branche.

`git push` please :wink:

**Comment by Simounet** [comment]
Je n'avais pas poussé sur le bon dépôt. C'est corrigé.

**Comment by Simounet** [comment]
Je pensais avoir déjà poussé ça. Il n'est jamais trop tard. #492 a été fusionné sur `dev`. Je ferme donc cette issue.
