### ISSUE TITLE
Soucis au niveau du cache de templates

### ISSUE THREAD

**Issue by FlorianneRaven** [LeedRSS/Leed#479]
Voici l'erreur que j'ai sur la page index.php:

Warning: count(): Parameter must be an array or an object that implements Countable in "..."/cache/tmp/index.22cbc366a97a7f8a434511ca3bbd2a81.rtpl.php on line 83

voici la ligne en question:
"<?php if( count($feeds)!=0 ){ ?>"

**Comment by FlorianneRaven** [comment]
J'ai trouvé pourquoi.
Quand un dossier n'a pas de flux dedans, ça provoque ce bug

**Comment by Sbgodin** [comment]
Excellent ! Merci pour la recherche. Je m'y colle !

**Comment by Simounet** [comment]
Tu ne devrait plus avoir de soucis avec la dernière version de la branche `dev`. Merci pour ta participation ! Ça fait plaisir de voir qu'il y a encore des personnes qui utilisent Leed. 👍
