### ISSUE TITLE
[feedburner.com] Aucun flux n'a pu être trouvé

### ISSUE THREAD

**Issue by HacKurx** [LeedRSS/Leed#481]
Bonjour, 

Les flux RSS utilisant feedburner.com ne fonctionnent pas chez moi. Voici l'erreur : 
`A feed could not be found at https://feeds.feedburner.com/Command-line-fu. This does not appear to be a valid RSS or Atom feed.`

Avez-vous le même problème avec le flux ci-dessus ?
Avez-vous envisagé une mise à jour de [SimplePie](https://github.com/simplepie/simplepie/releases) 1.4.3 vers 1.5.2 ?

Merci

**Comment by Simounet** [comment]
C'est étrange, j'ai des flux ayant cette source mais je n'ai jamais eu de soucis. Merci pour avoir mis à jour SimplePie et désolé pour l'absence de réponse…
Je ferme ce ticket si tu n'y vois pas d'inconvénient.

**Comment by HacKurx** [comment]
> Je ferme ce ticket si tu n'y vois pas d'inconvénient.

Pas de problème ;)
