### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by worldworm** [LeedRSS/Leed#482]
your site is not available.

If the URL has changed, please open a pull request at 
https://github.com/Kickball/awesome-selfhosted or create an issue. Thank you!

https://github.com/Kickball/awesome-selfhosted/issues/1767

**Comment by Simounet** [comment]
Thanks a lot, I've created an issue about that https://github.com/Kickball/awesome-selfhosted/pull/1776 .
Have a nice day.
