### ISSUE TITLE
Le site web est KO

### ISSUE THREAD

**Issue by azmeuk** [LeedRSS/Leed#483]
Le [lien](http://projet.idleman.fr/leed) affiché sur la page d'accueil du projet github est KO.

**Comment by Simounet** [comment]
C'est corrigé. Je l'ai supprimé.

**Comment by azmeuk** [comment]
Salut. Le lien est encore présent dans le README :)
Par ailleurs, y a-t-il un site officiel ou seulement le dépôt github ?

**Comment by Simounet** [comment]
C'est corrigé. J'ai mis à jour le README. Il y avait un site qui a disparu et il n'y a que le dépôt. Peut-être un jour y aura-t-il autre chose.
Merci encore et bonne soirée.
