### ISSUE TITLE
PHP Warning count() en PHP 7.3

### ISSUE THREAD

**Issue by spyjo** [LeedRSS/Leed#485]
Bonjour,

Suite à la migration de mon serveur en PHP 7.3, j'ai l'erreur suivante qui apparait dans les logs:

`[11-Jan-2020 03:12:39 Europe/Paris] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/mydomain.com/web/rss/leed/cache/tmp/index.22cbc366a97a7f8a434511ca3bbd2a81.rtpl.php on line 83`

Dans ce fichier ça correspond à cette ligne:
`<?php if( count($feeds)!=0 ){ ?>`

Dans le fichier du template correspondant "/templates/marigolds/index.html" ça correspond à cette ligne:
`{if="count($feeds)!=0"}`

Cordialement

**Comment by Simounet** [comment]
Hello,
Aurais-tu un moyen de tester la correction poussée sur la branche [dev](https://github.com/LeedRSS/Leed/tree/dev) ?

**Comment by spyjo** [comment]
Merci, plus de soucis avec la branche dev ;)

**Comment by Simounet** [comment]
C'est poussé sur master et j'en ai profité pour faire une release. Merci pour ton retour rapide et d'utiliser Leed. :)
Bonne soirée.
