### ISSUE TITLE
Incompatibilité leed avec php 8

### ISSUE THREAD

**Issue by Neurozone** [LeedRSS/Leed#495]
Deprecated: Required parameter $order follows optional parameter $start in Feed.class.php on line 252

Deprecated: Required parameter $order follows optional parameter $start in Event.class.php on line 70

Deprecated: Required parameter $order follows optional parameter $start inFolder.class.php on line 28

**Comment by Simounet** [comment]
Hello @Neurozone ,
Désolé pour la réponse tardive et merci pour ta vigilance une fois de plus. Pourrais-tu tester la branche `feat/php8-compliant` ? J'ai fait les modifications nécessaires.

**Comment by Neurozone** [comment]
Il faut que je réinstaller une instance de leed, l'ayant forké pour mon besoin et je n'avais pas vu le message noyé dans la tonne d'email que je reçois

**Comment by Simounet** [comment]
Pas de soucis et merci d'avance !

**Comment by Neurozone** [comment]
D'ailleurs si on peut parler de tout ça, j'aimerais bien le faire, il y a moyen de se contacter ?

**Comment by Simounet** [comment]
Bien sûr contact at simounet net.

**Comment by Philippe-M** [comment]
Bonjour, je rencontre le même problème avec php 8.0.20.

**Comment by Simounet** [comment]
Bonjour @Philippe-M pourrais-tu tester la branche feat/php8-compliant ? J'ai fait les modifications nécessaires. Merci d'avance et désolé pour la réponse tardive !

**Comment by Simounet** [comment]
Normalement, le soucis est réglé par [la version 1.10.0](https://github.com/LeedRSS/Leed/releases/tag/v1.10.0). N'hésitez pas à ouvrir à nouveau cette issue si ce n'est pas le cas.
