### ISSUE TITLE
Incompatibilité avec certain mysql 8

### ISSUE THREAD

**Issue by grimlokason** [LeedRSS/Leed#496]
Bonjour,

Je passe ma bdd d'un mariadb en docker local vers une instance cloud publique.

Je rencontre cette erreur avec la nouvelle BDD :
 ```
NOTICE: PHP message: Leed error: Unknown column 'grim_lokason' in 'where clause'
NOTICE: PHP message: Leed query: SELECT * FROM `leed__user`  WHERE `login`="grim_lokason" LIMIT 1 ;
```

En la testant, directement avec le client mysql, elle échoue belle et bien.
Par contre, celle ci passe : 
```
SELECT * FROM `leed__user`  WHERE `login`=`grim_lokason` LIMIT 1 ;
```

je ne sais pas ou effectuer les modifications dans le code pour le rendre de nouveau fonctionnel

Merci d'avance !

**Comment by Simounet** [comment]
Bonjour @grimlokason ,

Déjà, désolé pour la réponse tardive. J'ai fait quelques recherches et j'ai l'impression que ton soucis vient du mode [`ANSI_QUOTES`](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_ansi_quotes) définit par ton nouvel hébergeur ([DigitalOcean](https://www.digitalocean.com/community/questions/sql-requests-with-double-quotes-not-working-with-managed-database) ?) qui interprète les `"` comme des identifiants et plus comme des chaînes de caractères classiques.

J'ai bien vu ta merge request mais juste pour être sûr que ce soit bien ça, pourrais-tu lancer la commande `SELECT @@sql_mode;` via ton client mysql et me retourner le résultat s'il te plaît ?

**Comment by grimlokason** [comment]
Bonjour @Simounet 

Merci pour ton retour.

Voici le retour de la commande demandée, et il y a bel et bien le ANSI_QUOTES : 
```sql
MySQL [(none)]> SELECT @@sql_mode;
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                                                                                      |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| REAL_AS_FLOAT,PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,ONLY_FULL_GROUP_BY,ANSI,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.001 sec)
```

NB : C'était chez OVH via leur bêta de DBaaS, mais je vais détruire la bdd ce soir ^^'

**Comment by Simounet** [comment]
Ton correctif est fusionné dans la branche `dev`. Ça sera disponible dans la v1.9.3. Je ferme !

**Comment by Simounet** [comment]
Salut @grimlokason ,
J'essaie de relancer les choses du côté de Leed et j'ai besoin de savoir comment les gens l'utilisent. Si tu as 2mn, pourrais-tu me contacter par mail à leed at simounet point net ? Merci d'avance !
