### ISSUE TITLE
Problème avec certains caractères spéciaux

### ISSUE THREAD

**Issue by Bagu** [LeedRSS/Leed#498]
Bonjour,

J'utilise la dernière version disponible sur git (mais le problème existait aussi avec la version 1.9.0) et certains titres laissent apparaitre le caractère `&#8217;`
Il semble que `&#8217;` soit remplacé par `&amp;#8217;` au lieu d'une apostrophe.
Sauriez-vous comment corriger ce problème ?

Merci

EDIT : Je précise que cela n'arrive que dans les titres. L'article en lui même n'a pas ce soucis.

**Comment by Bagu** [comment]
Bon, ben en attendant une meilleure solution, j'ai fait ce qui suit...
Dans Feed.class.php, ligne 104, remplacer : 
`$event->setTitle($item->get_title());`
Par : 
`$event->setTitle(html_entity_decode(htmlspecialchars_decode($item->get_title())));`

De ce que j'en ai vu, cela vient d'un flux ne respectant pas bien les normes.
Donc simplepie encode `&#8217;` par `&amp;#8217;`

**Comment by Simounet** [comment]
Bonjour,

Aurais-tu le lien d'un flux que je regarde ça ? J'ai le problème actuellement sur [Numerama ](https://www.numerama.com/feed/) mais le flux contient bien `&amp;#8217;`, pas besoin que SimplePie remplace quoi que ce soit. Je voudrais juste être sûr qu'on parle bien du même soucis.

**Comment by Bagu** [comment]
C'est sur numerama que j'ai le soucis.
Comme dit précédemment, la modif fait le job, mais même si je n'ai pas eu de soucis, je préfère avoir un retour d'expérience d'un vrai dev ;)

**Comment by Simounet** [comment]
Ok, merci pour ton retour rapide et il n'y pas de vrai dév', toute aide est toujours appréciée ! Merci pour le code, je vais regarder de mon côté. ;)

**Comment by Simounet** [comment]
Je suis en train de tester ta solution de mon côté. Je ne vois pas pourquoi ça ne fonctionnerait pas. En attendant, j'ai corrigé les événements déjà présents en base en lançant ces commandes SQL :
```sql
UPDATE leed__event SET title=REPLACE(title, '&amp;#8217;', '’') WHERE title LIKE "%&amp;#8217;%";
UPDATE leed__event SET title=REPLACE(title, '&amp;#8230;', '…') WHERE title LIKE "%&amp;#8230;%";
UPDATE leed__event SET title=REPLACE(title, '&amp;#8212;', '—') WHERE title LIKE "%&amp;#8212;%";
UPDATE leed__event SET title=REPLACE(title, '&amp;#8211;', '–') WHERE title LIKE "%&amp;#8211;%";
UPDATE leed__event SET title=REPLACE(title, '&amp;#8217;', '’') WHERE title LIKE "%&amp;#8217;%";
UPDATE leed__event SET title=REPLACE(title, '&amp;#038;', '&') WHERE title LIKE "%&amp;#038;%";
UPDATE leed__event SET title=REPLACE(title, '&amp;#8243;', '″') WHERE title LIKE "%&amp;#8243;%";
```

La référence à la table `leed__event` peut changer en fonction du préfixe que tu as choisi.

**Comment by Simounet** [comment]
Je ferme ce ticket car j'ai poussé ton correctif sur la branche `dev` (f45f6987abf2eb9b591740444aa57ea778e0b658). Il sera dans la prochaine release v1.9.2. Merci pour ton aide !
