### ISSUE TITLE
common.php Mist à jour LEED_VERSION_NUMBER et LEED_VERSION_NAME

### ISSUE THREAD

**Issue by jarobase** [LeedRSS/Leed#499]
Les constantes définies dans le fichier common.php référencent toujours la version beta précédente:
define('LEED_VERSION_NUMBER','1.8.4');
define('LEED_VERSION_NAME','dev');

Une mise à jour de ces variables pour indiquer la dernière version (1.9.0 stable) serait bienvenue.

Merci pour le travail accompli :-).

**Comment by Simounet** [comment]
Salut merci beaucoup pour ce rappel. Je viens de pousser tout ça. Je vais créer une version `1.9.1` officielle dans la foulée. Bonne soirée !

**Comment by Simounet** [comment]
Salut @jarobase ,
J'essaie de relancer les choses du côté de Leed et j'ai besoin de savoir comment les gens l'utilisent. Si tu as 2mn, pourrais-tu me contacter par mail à leed at simounet point net ? Merci d'avance !
