### ISSUE TITLE
Deprecated: assert(): Calling assert()

### ISSUE THREAD

**Issue by Philippe-M** [LeedRSS/Leed#501]
Bonjour,

Je viens de changer d'hébergeur (Ovh -> infomaniak.ch) et j'en ai profité pour passer à la version 1.91. de LeedRss.

Le problème est que sur toute les pages j'ai le message :

` Deprecated: assert(): Calling assert() with a string argument is deprecated in /home/clients/.../i18n.php on line 47`

Le problème est présent avec PHP : 7.4.30 mais disparait en version 8.0.20

**Comment by Simounet** [comment]
Bonjour,
Pourrais-tu tester la branche `feat/php8-compliant` ? Merci d'avance et désolé pour la réponse tardive.

**Comment by Simounet** [comment]
Normalement, le soucis est réglé par [la version 1.10.0](https://github.com/LeedRSS/Leed/releases/tag/v1.10.0). N'hésite pas à ouvrir à nouveau cette issue si ce n'est pas le cas.

**Comment by Simounet** [comment]
Salut @Philippe-M ,
J'essaie de relancer les choses du côté de Leed et j'ai besoin de savoir comment les gens l'utilisent. Si tu as 2mn, pourrais-tu me contacter par mail à leed at simounet point net ? Merci d'avance !
