### ISSUE TITLE
PHP 8.1 - problème de compatibilité ?

### ISSUE THREAD

**Issue by Bagu** [LeedRSS/Leed#503]
Bonjour,

J'utilise la dernière version de Leedrss et j'ai dû mettre à jour php vers la version 8.1.
Le problème, c'est que depuis, j'ai un problème avec la ligne 70 de common.php.
Si je ne la commente pas, je reçois l'erreur suivante dans les logs et une jolie page blanche : 
```
[12-Sep-2022 12:42:25 Europe/Paris] PHP Fatal error:  Uncaught TypeError: Cannot assign null to property mysqli::$affected_rows of type string|int in \common.php:70
Stack trace:
#0 \common.php(70): unserialize()
#1 \header.php(6): require_once('...')
#2 \index.php(9): require_once('...')
#3 {main}
  thrown in \common.php on line 70
[12-Sep-2022 12:45:19 Europe/Paris] PHP Parse error:  syntax error, unexpected token ")" in \common.php on line 70
```

Auriez-vous une idée de l'origine et de la correction à apporter ?

**Comment by Simounet** [comment]
Bonjour @Bagu , pourrais-tu tester la branche `feat/php8-compliant` qui devrait régler le problème de ton premier message.

Pour ce qui est de ton deuxième message, pourrais-tu me dire les étapes suivies pour arriver à ces erreurs en utilisant la navigation privée pour repartir du début.

Merci d'avance.

**Comment by Bagu** [comment]
Je viens de mettre la version php8-compliant.
Je verrais si de nouvelles erreurs sont remontée car les erreurs du second message ne sont pas apparues suite à une action de ma part.
Je suspecte donc que cela arrive lors des synchro automatiques des news.

Pour info, mes sources sont les suivantes : 
Bons plans - NextInpact
Freenews.fr
Le Monde
Numerama
Sciences et Avenir
Techno-Science.net

**Comment by Simounet** [comment]
Super, j'attends ton retour.

**Comment by Bagu** [comment]
Bonsoir,

J'ai isolé un message d'erreur avec sa cause :
```
[20-Sep-2022 21:54:19 Europe/Paris] Leed: wrong login for ''
[21-Sep-2022 00:30:07 Europe/Paris] Leed: wrong login for ''
```

Cela arrive lorsque l'on tente de s'authentifier en laissant les champs identifiants et mot de passe vides

J'ai d'autres messages, mais je tente encore de comprendre comment les reproduire.

**Comment by Simounet** [comment]
Ce message est normal. Il est utilisé pour bloquer les personnes mal intentionnées essayant de se loguer. As-tu de nouveau eu ces erreurs :
```
[20-Sep-2022 00:22:16 Europe/Paris] PHP Fatal error:  Uncaught Error: Call to a member function unreadCount() on bool in \index.php:95
Stack trace:
#0 {main}
  thrown in E:\www\wwwbagubiz\html\www\index.php on line 95
[20-Sep-2022 06:45:46 Europe/Paris] PHP Fatal error:  Uncaught Error: Call to a member function unreadCount() on bool in \index.php:95
Stack trace:
#0 {main}
  thrown in \index.php on line 95
[20-Sep-2022 08:28:24 Europe/Paris] PHP Fatal error:  Uncaught Error: Call to a member function unreadCount() on bool in \index.php:95
Stack trace:
#0 {main}
  thrown in \index.php on line 95
```

**Comment by Bagu** [comment]
Bonjour,

Pour le moment, ces erreurs n'apparaissent plus.
Par contre, est-il possible d'éviter les log de connexions infructueuses ?

De même, je suppose que : 
```
[20-Sep-2022 21:54:19 Europe/Paris] PHP Warning:  Undefined array key "login" in \action.php on line 466
[20-Sep-2022 21:54:19 Europe/Paris] PHP Warning:  Undefined array key "password" in \action.php on line 466
[20-Sep-2022 21:54:19 Europe/Paris] PHP Warning:  Undefined array key "login" in \action.php on line 468
```

Est lié a la même problématique... Ou pas ?

**Comment by Simounet** [comment]
Non, pour le moment, les connexions infructueuses restent dans les logs.

Et les warnings ne sont en revanche pas souhaités. Tu obtiens ça en laissant les champs de login et password vides ? Tu es en PHP8.1, c'est ça ?

**Comment by Bagu** [comment]
Pour `Leed: wrong login for ''` oui, c'est en laissant tout vide
Pour [Undefined array key "login" in \action.php on line 466](url) et compagnie, non, c'est apparu dans la soirée sans action de ma part

Je suis bel et bien avec PHP 8.1.10 (pour être précis)

**Comment by Simounet** [comment]
Pour le `Undefined array key "login" in \action.php on line 466`, quelles actions fais-tu pour l'avoir ? Charger une page ? Effectuer une action particulière ?

**Comment by Bagu** [comment]
Comme écrit : C'est apparu en soirée sans aucune action de ma part.
Sachant que mon installation est visible ici : https://www.bagu.biz si besoin

**Comment by Simounet** [comment]
Mais dans les logs, elle continue d'apparaître à chaque action ?
Pour le bug d'encodage, je vais pousser la modification que tu as suggérée, elle fonctionne parfaitement depuis des mois de mon côté.

**Comment by Bagu** [comment]
Non, elle est apparue hier mais rien d'autre pour le moment.
Je suspecte un bot d'avoir tenté une connexion indésirable ou par des moyens détournés.

Mais pour le moment, ces messages ne réapparaissent pas.
J'ai activé les logs d'accès apache afin de confirmer mon hypothèse au cas où elle devait revenir.

**Comment by Bagu** [comment]
Après quelques jours, l'erreur est réapparu.
```
[22-Sep-2022 08:46:06 Europe/Paris] PHP Fatal error:  Uncaught Error: Call to a member function getId() on bool in index.php:80
Stack trace:
#0 {main}
  thrown in \index.php on line 80
[22-Sep-2022 17:04:54 Europe/Paris] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string - int in \index.php:132
Stack trace:
#0 {main}
  thrown in \index.php on line 132
```

Je ne sais pas comment elles sont arrivées, avec un doute un lien vis à vis de la récupération de news... Mais sans aucune certitude.

**Comment by Simounet** [comment]
J'ai mis à jour la branche php8-compliant pour la 2ème erreur. Par contre, je n'arrive pas à voir comment tu as eu la première. Elle doit apparaître quand tu sélectionnes un flux directement via l'interface. Pourrais-tu confirmer ?

**Comment by Bagu** [comment]
Salut,
Je viens de tester la sélection des flux. J'ai tout trituré, pas d'erreur. Je ne comprends pas d'où sort cette erreur. Je vais continuer à chercher.

**Comment by Simounet** [comment]
Ça marche. Merci pour ta persévérance, ça dégage pas mal de soucis. ;)

**Comment by Simounet** [comment]
J'ai l'impression que tu es en auto-hébergement, sur quelle machine héberges-tu Leed ? Quel système ? Apache ou Nginx ? PHP ou PHP-FPM ?
Merci d'avance.

**Comment by Bagu** [comment]
Oui, je suis en auto-hébergement :
Apache Apache 2.4.54
PHP 8.1.10 + FCGID 2.3.10

**Comment by Bagu** [comment]
Ok, l'erreur suivante : 
```
[24-Sep-2022 20:48:15 Europe/Paris] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string * string in \article.php:51
Stack trace:
#0 {main}
  thrown in \article.php on line 51
```
Apparait sur la page d'accueil et empêche de faire défiler toutes les news
Et elle apparait sur la branche dev php8

**Comment by Simounet** [comment]
J'ai vu passer l'erreur sur `article.php`, je viens de la corriger, toujours sur la même branche.

**Comment by Bagu** [comment]
Bon, de ce que j'en vois, il ne reste que : 
```
[25-Sep-2022 13:11:21 Europe/Paris] PHP Fatal error:  Uncaught Error: Call to a member function getId() on bool in \index.php:80
Stack trace:
#0 {main}
  thrown in \index.php on line 80
```
comme erreur récurrente. Par contre, je ne parviens pas à isoler un déclencheur.

Tout le reste est nickel, plus de problèmes de scroll, plus de problème de caractères spéciaux, et plus d'autres erreurs PHP.
Joli boulot 👍

**Comment by Simounet** [comment]
Super, j'ai commit une modification qui devrait empêcher cette dernière erreur. On va y arriver !

**Comment by Bagu** [comment]
Impec, j'ai poussé les modifications, je teste et te fais un retour.

**Comment by Bagu** [comment]
Bon, rien à faire, suite au dernier commit lié aux dossiers, j'ai deux erreurs qui réapparaissent sans cesse.
```
[30-Sep-2022 15:31:46 Europe/Paris] PHP Warning:  Undefined variable $currentFeed in \cache\tmp\index.393cf5ea8cc2646cedd2169c73a46c57.rtpl.php on line 202
[30-Sep-2022 15:31:46 Europe/Paris] PHP Fatal error:  Uncaught Error: Call to a member function getWebSite() on null in \cache\tmp\index.393cf5ea8cc2646cedd2169c73a46c57.rtpl.php:202
Stack trace:
#0 \RainTPL.php(175): include()
#1 \footer.php(4): RainTPL->draw()
#2 \index.php(163): require_once('...')
#3 {main}
  thrown in \cache\tmp\index.393cf5ea8cc2646cedd2169c73a46c57.rtpl.php on line 202
```
J'ai repris le code directement de github au lieu de le faire à la main, mais le problème reste le même et persiste.

**Comment by Bagu** [comment]
Bonjour,

C'est déjà fait... Deux fois.
J'ai mis toutes les chances de mon côté avant de reposter ici ;)

**Comment by Simounet** [comment]
Les erreurs remontent sur n'importe quelle page ? Même quand tu n'as pas sélectionné un flux en particulier ?

**Comment by Bagu** [comment]
En fait, ce qui est frustrant, c'est que cette erreur apparait entre 1 et deux fois par jour, mais à des moment où je ne consulte pas la page de news.
N'étant pas le seul à la visiter, je ne sais pas ce qui peut déclencher cette erreur.
Pire, quand je clique sur chaque flux et chaque dossiers, l'erreur ne vient pas.
Donc je ne sais pas la reproduire manuellement.

**Comment by Simounet** [comment]
Je pense avoir compris, peux-tu récupérer les dernières modifications sur la branche `feat/php8-compliant` ?
Pour voir ce qui se passe, tu dois avoir des requêtes de ce style dans tes logs d'accès :
```
GET /dev/Leed/?action=selectedFeed&feed= HTTP/2.0
```
Soit le paramètre `feed` ou `folder` est vide.

**Comment by Bagu** [comment]
Bon, après quelques jours, l'erreur ci-dessus n'apparait plus.... Mais elle est remplacée ^^
```
[05-Oct-2022 06:24:49 Europe/Paris] PHP Fatal error:  Uncaught TypeError: htmlspecialchars(): Argument #1 ($string) must be of type string, array given in \Functions.class.php:23
Stack trace:
#0 \Functions.class.php(23): htmlspecialchars()
#1 \common.php(110): Functions::secure()
#2 \header.php(6): require_once('...')
#3 \index.php(9): require_once('...')
#4 {main}
  thrown in \Functions.class.php on line 23
[05-Oct-2022 11:02:53 Europe/Paris] PHP Warning:  Undefined array key "login" in \action.php on line 466
[05-Oct-2022 11:02:53 Europe/Paris] PHP Warning:  Undefined array key "password" in \action.php on line 466
```

**Comment by Simounet** [comment]
J'ai mis à jour la branche. #onlâcherien

**Comment by Bagu** [comment]
Déployé - J'attends de voir

**Comment by Bagu** [comment]
Hello,

Les nouvelles sont mitigées : 
La bonne nouvelle : je n'ai plus eu de message d'erreur
La mauvaise : impossible de me connecter

Y-a-t'il eu une modification sur la gestion du login ?

**Comment by Simounet** [comment]
J'en avais oublié un bout. Peux-tu mettre à jour s'il te plaît ?

**Comment by Bagu** [comment]
Déployé - login impec et pas d'erreurs/warning pour le moment
Je vais le torturer un peu ce soir histoire de voir si c'est bon.

**Comment by Simounet** [comment]
Désolé pour le soucis et encore merci pour ton retour !

**Comment by Bagu** [comment]
He ben good job...
Ça fait une bonne heure que je torture mon installation sans que cela ne lève une quelconque erreur ni aucun avertissement.
Donc pour ma part, c'est validé ! 👍

**Comment by Simounet** [comment]
C'est une belle étape. Merci pour ton implication !
