### ISSUE TITLE
Problème de variable $otpEnable

### ISSUE THREAD

**Issue by Bagu** [LeedRSS/Leed#509]
Bonjour,

J'utilise LeedRss en version 1.13 avec php 8.1.27 et apache.
Depuis la version 1.13, j'observe deux erreurs récurrentes :
```
[02-Jan-2024 04:49:10 Europe/Paris] PHP Warning:  Undefined variable $otpEnabled in \cache\tmp\header.393cf5ea8cc2646cedd2169c73a46c57.rtpl.php on line 47
[02-Jan-2024 04:52:14 Europe/Paris] Invalid language: '*;'
```

OTP n'est pas actif.

J'ai tenté de multiple choses (effacement du cache, changement de version de PHP...) et impossible de corriger le soucis.
Auriez-vous une piste sur l'origine du soucis ?
Merci

**Comment by Simounet** [comment]
Hello,
Peux-tu supprimer tous les fichiers présents dans `cache/tmp` ?
As-tu essayé dans un navigateur en mode navigation privée ? Dans ta session courante, essaies de te déconnecter/reconnecter.

**Comment by Simounet** [comment]
Pourrais-tu faire un `grep -r otpEnabled .` quand tu es dans le répertoire de Leed ?

**Comment by Bagu** [comment]
How nom d'une pipe !
Bien vu !
J'ai fait une variante bleu du thème marigold, et j'avais oublié de répercuter les changements, notamment la suppression d'OTP.
Une fois le thème corrigé, le cache vidé, tout est bon.
Merci beaucoup ;)

**Comment by Simounet** [comment]
Le principal, c'est que ça fonctionne. Bonne soirée.
