### ISSUE TITLE
PHP 8.4 - Function Deprecation Errors

### ISSUE THREAD

**Issue by alatnet** [LeedRSS/Leed#510]
Recently updated my php installation and leed is throwing some deprecation errors when updating my feeds.

> Deprecated: SimplePie\Sanitize::pass_cache_data(): Implicitly marking parameter $cache as nullable is deprecated, the explicit nullable type must be used instead in /usr/share/nginx/html/leed/SimplePie.class.php on line 15914
> 
> Deprecated: Function xml_set_object() is deprecated since 8.4, provide a proper method callable to xml_set_*_handler() functions in /usr/share/nginx/html/leed/SimplePie.class.php on line 14894
> 
> Deprecated: xml_set_character_data_handler(): Passing non-callable strings is deprecated since 8.4 in /usr/share/nginx/html/leed/SimplePie.class.php on line 14895
> 
> Deprecated: xml_set_element_handler(): Passing non-callable strings is deprecated since 8.4 in /usr/share/nginx/html/leed/SimplePie.class.php on line 14896
> 
> Deprecated: Function xml_set_object() is deprecated since 8.4, provide a proper method callable to xml_set_*_handler() functions in /usr/share/nginx/html/leed/SimplePie.class.php on line 14894
> 
> Deprecated: xml_set_character_data_handler(): Passing non-callable strings is deprecated since 8.4 in /usr/share/nginx/html/leed/SimplePie.class.php on line 14895
> 
> Deprecated: xml_set_element_handler(): Passing non-callable strings is deprecated since 8.4 in /usr/share/nginx/html/leed/SimplePie.class.php on line 14896

For the first one, it seems that you can fix that one easily enough by adding a '?' to the beginning of the DataCache type in the parameter.

The others... well... I'm still trying to figure that one out atm.

**Comment by Simounet** [comment]
Hi there,
I just pushed an update for SimplePie that should fix the deprecations. Will check for the other issues.

**Comment by alatnet** [comment]
Yep, no errors after replacing that file with the updated version.
